from __future__ import annotations

from typing import Any, Protocol

from ai_quant_trader.core.models import OrderRequest, OrderResult, PositionSnapshot


class BaseExchangeGateway(Protocol):
    """交易网关统一协议。

    业务层只依赖这个协议，不直接关心模拟盘或实盘。这样运行模式切换只发生在工厂层，
    避免核心交易代码里散落 if dry_run / if mock 之类的分支。
    """

    mode: str

    async def check_connectivity(self) -> bool: ...

    async def fetch_balance_summary(self) -> dict[str, Any]: ...

    async def fetch_positions(self, symbols: list[str]) -> list[PositionSnapshot]: ...

    async def fetch_open_orders(self, symbols: list[str]) -> list[dict[str, Any]]: ...

    async def minimum_order_amount(self, symbol: str, price: float | None = None) -> float: ...

    async def minimum_order_check(self, symbol: str, price: float | None = None) -> dict[str, Any]: ...

    async def contract_size(self, symbol: str) -> float: ...

    async def create_market_order(self, request: OrderRequest) -> OrderResult: ...

    async def create_stop_loss_order(self, request: OrderRequest, stop_price: float, price_type: int = 1) -> OrderResult: ...

    async def find_order_by_client_order_id(self, symbol: str, client_order_id: str) -> OrderResult | None: ...

    async def fetch_order_by_exchange_id(self, symbol: str, exchange_order_id: str) -> OrderResult | None: ...

    async def cancel_order(self, symbol: str, order_id: str, *, trigger: bool = False) -> bool: ...

    async def close_position(self, symbol: str, reason: str = "manual_close") -> OrderResult | None: ...

    async def close_positions(self, symbols: list[str], reason: str = "panic_close") -> list[OrderResult]: ...

    async def close(self) -> None: ...
