[Definition]
failregex = ^<HOST> - .* "(GET|POST|HEAD) .*(?:\.env|/\.git|php://filter|convert\.base64-encode|\.\./|%%2e%%2e|%%252e%%252e|wp-admin|wp-login|/etc/passwd).*" (?:400|403|404) .*
ignoreregex =
